FROM node:20-alpine

RUN apk update && apk upgrade --no-cache

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install tailwindcss @tailwindcss/vite
RUN npm install react-router-dom lucide-react
RUN npx shadcn@latest init --preset b1Z5bbEAK --template vite
RUN npx shadcn@latest add button empty spinner sheet dialog

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]